spring:
  web:
    resources:
      add-mappings: false

  # Datasource 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blossom?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: 'root'
    password: qwer1234
    hikari:
      pool-name: jpa-hikari-pool
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
#      idleTimeout: 300
#      maxLifeTime: 300
      data-source-properties:
        rewriteBatchedStatements: true

  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true

  # Security OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "3543889d4182152b52063b887ed4d265"
            client-secret: "a2HbN3KNTqRYb6s8anEJUZjbwXtfmuV3"
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
          naver:
            client-id: "VthzV0S1RkbcE9znrWYe"
            client-secret: "NgJt0YJShU"
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
          google:
            clientId: "97605122659-617hhbt2rrrdub4qkibd2d4lno5dhmmq.apps.googleusercontent.com"
            clientSecret: "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"
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  cloud:
    aws:
      s3:
        endpoint: https://kr.object.ncloudstorage.com
        region: ap-northeast-2
        credentials:
          access-key: w5Xs6uxbuOJPu7vt63VQ
          secret-key: o8m7M2SppOnIte8UqyP4Uw6BDHhW7VrSdvRxICSV
          bucket: blossom-bucket

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: 8w3h4jhofufj8e99hn3ow2j8w9uefrfjr9f384o238rt3jfer9th498fejhq490rfjjhtwrggh488ewh34oq4f
  access-token-expire-period: 7200
  refresh-token-expire-period: 1209600

server:
  client-address: http://localhost:5173

crypt:
  key: diejfkslwodnflsnvidowhfkdiehskds

